/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sun' at '24/07/16 22:06' with Gradle 2.14.1
 *
 * @author sun, @date 24/07/16 22:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
